# Generated by GitHub Copilot
"""Inference unit tests for WAV decoding and score contracts."""

from __future__ import annotations

from io import BytesIO

import numpy as np
import soundfile as sf

from src.infer import predict_emotion_from_audio
from src.model import default_model


def _make_wav(duration_seconds: float = 1.0, sample_rate: int = 16000) -> bytes:
    """Create deterministic sine-wave WAV bytes for tests."""

    sample_count = int(duration_seconds * sample_rate)
    timeline = np.linspace(0, duration_seconds, sample_count, endpoint=False)
    audio = 0.2 * np.sin(2 * np.pi * 220 * timeline).astype(np.float32)

    buffer = BytesIO()
    sf.write(buffer, audio, sample_rate, format="WAV")
    return buffer.getvalue()


def test_predict_emotion_from_audio_returns_valid_payload():
    """Inference should return expected keys and bounded confidence values."""

    model = default_model()
    payload = predict_emotion_from_audio(_make_wav(), model)

    assert payload["emotion"] in payload["scores"]
    assert 0.0 <= payload["confidence"] <= 1.0
    assert payload["duration_seconds"] > 0
    assert payload["sample_rate_hz"] == 16000


def test_predict_emotion_from_audio_rejects_short_audio():
    """Inference should reject audio shorter than the minimum configured duration."""

    model = default_model()
    try:
        predict_emotion_from_audio(_make_wav(duration_seconds=0.1), model)
    except ValueError as exc:
        assert "too short" in str(exc)
        return

    raise AssertionError("Expected ValueError for short audio")
