// Generated by GitHub Copilot
import { useRef, useState } from "react";

const API_BASE_URL = import.meta.env.VITE_API_URL || "http://127.0.0.1:8001";

function App() {
    const mediaRecorderRef = useRef(null);
    const chunksRef = useRef([]);
    const [recording, setRecording] = useState(false);
    const [result, setResult] = useState(null);
    const [status, setStatus] = useState("Idle");

    /**
     * Start browser microphone capture with MediaRecorder.
     */
    async function startRecording() {
        const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
        const mediaRecorder = new MediaRecorder(stream);
        chunksRef.current = [];

        mediaRecorder.ondataavailable = (event) => {
            if (event.data.size > 0) {
                chunksRef.current.push(event.data);
            }
        };

        mediaRecorder.onstop = async () => {
            const blob = new Blob(chunksRef.current, { type: "audio/wav" });
            const file = new File([blob], "recording.wav", { type: "audio/wav" });
            const formData = new FormData();
            formData.append("file", file);

            setStatus("Analyzing...");
            const response = await fetch(`${API_BASE_URL}/predict`, {
                method: "POST",
                body: formData,
            });

            if (!response.ok) {
                setStatus("Prediction failed");
                return;
            }

            const payload = await response.json();
            setResult(payload);
            setStatus("Done");
        };

        mediaRecorderRef.current = mediaRecorder;
        mediaRecorder.start();
        setRecording(true);
        setStatus("Recording...");
    }

    /**
     * Stop active recording session and trigger prediction upload.
     */
    function stopRecording() {
        if (!mediaRecorderRef.current) {
            return;
        }
        mediaRecorderRef.current.stop();
        setRecording(false);
    }

    return (
        <main style={{ maxWidth: 640, margin: "40px auto", fontFamily: "Segoe UI, sans-serif" }}>
            <h1>speech-emotion-v2</h1>
            <p>Status: {status}</p>
            <div style={{ display: "flex", gap: 12 }}>
                <button type="button" onClick={startRecording} disabled={recording}>
                    Start Recording
                </button>
                <button type="button" onClick={stopRecording} disabled={!recording}>
                    Stop Recording
                </button>
            </div>

            {result && (
                <section style={{ marginTop: 24 }}>
                    <h2>Prediction</h2>
                    <p>
                        Emotion: <strong>{result.emotion}</strong>
                    </p>
                    <p>Confidence: {Number(result.confidence).toFixed(3)}</p>
                </section>
            )}
        </main>
    );
}

export default App;
