# Generated by GitHub Copilot
"""Inference helper functions for speech-emotion-v2."""

from __future__ import annotations

import numpy as np

EMOTIONS = ["neutral", "calm", "happy", "sad", "angry", "fearful", "disgust", "surprised"]


def predict_emotion_from_logits(logits: np.ndarray) -> dict[str, object]:
    """Convert model logits into emotion label and confidence score."""

    if logits.ndim != 1:
        raise ValueError("logits must be a 1D array")

    exp = np.exp(logits - np.max(logits))
    probs = exp / np.sum(exp)
    index = int(np.argmax(probs))

    return {
        "emotion": EMOTIONS[index],
        "confidence": float(probs[index]),
        "scores": {label: float(prob) for label, prob in zip(EMOTIONS, probs, strict=True)},
    }
