# Generated by GitHub Copilot
"""Lightweight model contract for speech emotion prototype classification."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
import json
from pathlib import Path

import numpy as np

EMOTIONS = ["neutral", "calm", "happy", "sad", "angry", "fearful", "disgust", "surprised"]
FEATURE_NAMES = ["energy", "zero_crossing", "peak_abs", "silence_ratio"]


@dataclass(frozen=True)
class PrototypeModel:
    """Container for deterministic centroid-based model metadata."""

    version: str
    feature_names: list[str]
    centroids: dict[str, list[float]]
    trained_at: str


def default_model() -> PrototypeModel:
    """Return a safe baseline model used when no trained artifact is available."""

    centroids = {
        "neutral": [0.12, 0.03, 0.35, 0.44],
        "calm": [0.09, 0.02, 0.28, 0.50],
        "happy": [0.20, 0.06, 0.62, 0.19],
        "sad": [0.06, 0.02, 0.18, 0.63],
        "angry": [0.26, 0.10, 0.88, 0.11],
        "fearful": [0.15, 0.08, 0.57, 0.21],
        "disgust": [0.11, 0.05, 0.40, 0.35],
        "surprised": [0.24, 0.12, 0.82, 0.10],
    }
    return PrototypeModel(
        version="baseline-1",
        feature_names=FEATURE_NAMES,
        centroids=centroids,
        trained_at=datetime.now(timezone.utc).isoformat(),
    )


def load_model(path: str | Path) -> PrototypeModel:
    """Load model artifact from disk or fallback to a safe baseline model."""

    candidate = Path(path)
    if not candidate.exists():
        model = default_model()
        save_model(model, candidate)
        return model

    payload = json.loads(candidate.read_text(encoding="utf-8"))
    return PrototypeModel(
        version=payload["version"],
        feature_names=payload["feature_names"],
        centroids=payload["centroids"],
        trained_at=payload["trained_at"],
    )


def save_model(model: PrototypeModel, path: str | Path) -> None:
    """Persist model artifact as JSON for API serving and rollback workflows."""

    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(asdict(model), ensure_ascii=True, indent=2), encoding="utf-8")


def score_feature_vector(model: PrototypeModel, features: np.ndarray) -> dict[str, float]:
    """Score one feature vector against model centroids and return probabilities."""

    if features.ndim != 1:
        raise ValueError("features must be a 1D vector")

    distances: dict[str, float] = {}
    for emotion in EMOTIONS:
        centroid = np.asarray(model.centroids[emotion], dtype=np.float32)
        distances[emotion] = float(np.linalg.norm(features - centroid))

    neg_dist = -np.array([distances[label] for label in EMOTIONS], dtype=np.float32)
    exp = np.exp(neg_dist - np.max(neg_dist))
    probs = exp / np.sum(exp)
    return {label: float(prob) for label, prob in zip(EMOTIONS, probs, strict=True)}
