# Generated by GitHub Copilot
"""Model construction utilities for wav2vec2 emotion classification."""

from transformers import Wav2Vec2ForSequenceClassification


def build_model(num_labels: int = 8, model_name: str = "facebook/wav2vec2-base"):
    """Build wav2vec2 sequence classification model for speech emotion tasks."""

    return Wav2Vec2ForSequenceClassification.from_pretrained(
        model_name,
        num_labels=num_labels,
        problem_type="single_label_classification",
    )
