# Generated by GitHub Copilot
"""Training entrypoint with optional MLflow tracking for speech emotion model."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import os
from pathlib import Path

import numpy as np

from .model import EMOTIONS, FEATURE_NAMES, PrototypeModel, save_model, score_feature_vector


def _build_dataset(seed: int, samples_per_emotion: int) -> tuple[np.ndarray, np.ndarray]:
    """Generate deterministic synthetic feature dataset used for baseline training."""

    rng = np.random.default_rng(seed)
    base_centroids = np.asarray(
        [
            [0.12, 0.03, 0.35, 0.44],
            [0.09, 0.02, 0.28, 0.50],
            [0.20, 0.06, 0.62, 0.19],
            [0.06, 0.02, 0.18, 0.63],
            [0.26, 0.10, 0.88, 0.11],
            [0.15, 0.08, 0.57, 0.21],
            [0.11, 0.05, 0.40, 0.35],
            [0.24, 0.12, 0.82, 0.10],
        ],
        dtype=np.float32,
    )

    features = []
    labels = []
    for idx in range(len(EMOTIONS)):
        cluster = rng.normal(loc=base_centroids[idx], scale=0.02, size=(samples_per_emotion, 4)).astype(np.float32)
        cluster = np.clip(cluster, 0.0, 1.0)
        features.append(cluster)
        labels.extend([idx] * samples_per_emotion)

    return np.vstack(features), np.asarray(labels, dtype=np.int64)


def _fit_centroids(features: np.ndarray, labels: np.ndarray) -> dict[str, list[float]]:
    """Fit per-emotion centroids over the generated feature vectors."""

    centroids: dict[str, list[float]] = {}
    global_centroid = np.mean(features, axis=0)
    for idx, emotion in enumerate(EMOTIONS):
        class_vectors = features[labels == idx]
        centroid = np.mean(class_vectors, axis=0) if class_vectors.size else global_centroid
        centroids[emotion] = [float(value) for value in centroid]
    return centroids


def _evaluate_model(model: PrototypeModel, features: np.ndarray, labels: np.ndarray) -> float:
    """Compute deterministic validation accuracy for release gating."""

    predictions = []
    for vector in features:
        scores = score_feature_vector(model, vector)
        predictions.append(EMOTIONS.index(max(scores, key=scores.get)))

    return float(np.mean(np.asarray(predictions, dtype=np.int64) == labels))


def run_training(
    output_model_path: str = "models/latest/model.json",
    version: str = "v0.2.0",
    seed: int = 42,
    samples_per_emotion: int = 200,
    experiment_name: str = "speech-emotion-v2",
) -> dict[str, float | str]:
    """Run model training, persist artifact, and optionally report metrics to MLflow."""

    features, labels = _build_dataset(seed=seed, samples_per_emotion=samples_per_emotion)

    rng = np.random.default_rng(seed)
    order = rng.permutation(features.shape[0])
    features = features[order]
    labels = labels[order]

    split_index = int(features.shape[0] * 0.8)
    train_features, val_features = features[:split_index], features[split_index:]
    train_labels, val_labels = labels[:split_index], labels[split_index:]

    centroids = _fit_centroids(train_features, train_labels)
    model = PrototypeModel(
        version=version,
        feature_names=FEATURE_NAMES,
        centroids=centroids,
        trained_at=datetime.now(timezone.utc).isoformat(),
    )
    save_model(model, output_model_path)

    val_accuracy = _evaluate_model(model, val_features, val_labels)
    summary: dict[str, float | str] = {
        "model_version": model.version,
        "validation_accuracy": val_accuracy,
        "artifact_path": str(Path(output_model_path).resolve()),
    }

    tracking_uri = os.getenv("MLFLOW_TRACKING_URI")
    enable_tracking = os.getenv("ENABLE_MLFLOW_TRACKING", "true").lower() == "true"
    if enable_tracking:
        try:
            import mlflow

            if tracking_uri:
                mlflow.set_tracking_uri(tracking_uri)
            mlflow.set_experiment(experiment_name)
            with mlflow.start_run():
                mlflow.log_param("model_version", model.version)
                mlflow.log_param("seed", seed)
                mlflow.log_param("samples_per_emotion", samples_per_emotion)
                mlflow.log_metric("validation_accuracy", val_accuracy)
                mlflow.log_artifact(output_model_path)
        except Exception as exc:  # pragma: no cover
            summary["mlflow_warning"] = f"Tracking skipped: {exc}"

    return summary


def parse_args() -> argparse.Namespace:
    """Parse command-line options for reproducible training runs."""

    parser = argparse.ArgumentParser(description="Train centroid-based speech emotion model")
    parser.add_argument("--output", default="models/latest/model.json", help="Output model artifact path")
    parser.add_argument("--version", default="v0.2.0", help="Model version tag")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument("--samples-per-emotion", type=int, default=200, help="Synthetic training volume")
    parser.add_argument("--experiment", default="speech-emotion-v2", help="MLflow experiment name")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    result = run_training(
        output_model_path=args.output,
        version=args.version,
        seed=args.seed,
        samples_per_emotion=args.samples_per_emotion,
        experiment_name=args.experiment,
    )
    print(result)
