# Generated by GitHub Copilot
"""Training entrypoint with MLflow tracking for speech emotion model."""

from __future__ import annotations

import mlflow

from .model import build_model


def run_training(experiment_name: str = "speech-emotion-v2") -> None:
    """Run a starter training workflow and log metadata in MLflow."""

    mlflow.set_experiment(experiment_name)
    with mlflow.start_run():
        mlflow.log_param("model_name", "facebook/wav2vec2-base")
        mlflow.log_param("dataset", "RAVDESS")

        model = build_model()
        mlflow.log_param("num_labels", model.config.num_labels)

        # Placeholder metrics until full data pipeline wiring is complete.
        mlflow.log_metric("train_loss", 0.0)
        mlflow.log_metric("val_accuracy", 0.0)


if __name__ == "__main__":
    run_training()
