# Generated by GitHub Copilot
"""FastAPI inference endpoint for uploaded speech audio."""

from __future__ import annotations

from fastapi import FastAPI, File, HTTPException, UploadFile
import numpy as np

from src.infer import predict_emotion_from_logits

app = FastAPI(title="speech-emotion-v2", version="0.1.0")


@app.get("/health")
def health() -> dict[str, str]:
    """Return API health status."""

    return {"status": "ok"}


@app.post("/predict")
async def predict(file: UploadFile = File(...)) -> dict[str, object]:
    """Accept a WAV upload and return predicted emotion with confidence."""

    if not file.filename.lower().endswith(".wav"):
        raise HTTPException(status_code=400, detail="Only .wav uploads are supported")

    raw = await file.read()
    if len(raw) == 0:
        raise HTTPException(status_code=400, detail="Empty file received")

    # Placeholder model output until wav2vec2 model serving is wired.
    logits = np.array([0.9, 0.2, 1.4, 0.1, 0.3, 0.1, 0.05, 0.2], dtype=np.float32)
    prediction = predict_emotion_from_logits(logits)
    prediction["bytes_received"] = len(raw)

    return prediction
